#  Copyright (C) 2026  EmGi

# You are free to modify it under the terms of the GNU General Public License as published by the Free Software Foundation.
# You are free to use any models Generated by this Addon Commercially

import os

import bpy

from . import addon_preferences, progress, props, temp, translation, updater, utils
from . import constants as const

try:
    from . import picker_server
except ImportError:
    picker_server = None
from bpy.app.handlers import persistent

from . import export, operators, panels

# Base (non-premium) classes — built once at import time.
# Premium classes are registered dynamically inside register() so that
# addon reload order (Blender may reload temp.py *after* __init__.py,
# resetting PREMIUMVERSION = False) cannot break detection.
classes = [
    progress.TP3D_OT_warnings_mouse,
    panels.TP3D_PT_generate,
    panels.TP3D_PT_advanced,
    panels.TP3D_PT_shapes,
    panels.TP3D_OT_show_custom_props_popup,
    operators.TP3D_OT_run_generation,
    operators.TP3D_OT_shapely_status,
    operators.TP3D_OT_earcut_status,
    operators.TP3D_OT_export_stl,
    operators.TP3D_OT_export_obj,
    operators.TP3D_OT_export_three_mf,
    operators.TP3D_OT_open_website,
    operators.TP3D_OT_join_discord,
    operators.TP3D_OT_rescale,
    operators.TP3D_OT_pin_coords,
    operators.TP3D_OT_terrain_dummy,
    operators.TP3D_OT_magnet_holes,
    operators.TP3D_OT_dovetail,
    operators.TP3D_OT_thicken,
    operators.TP3D_OT_bottom_mark,
    operators.TP3D_OT_color_mountain,
    operators.TP3D_OT_contour_lines,
    operators.TP3D_OT_save_preset,
    operators.TP3D_OT_load_preset,
    operators.TP3D_OT_delete_preset,
    operators.TP3D_OT_clear_cache,
    operators.TP3D_OT_import_svg,
    operators.TP3D_OT_popup_svg,
    operators.TP3D_OT_info_video,
    operators.TP3D_OT_popup_text,
    operators.TP3D_OT_import_text,
    operators.TP3D_OT_import_pin,
    operators.TP3D_OT_popup_pin,
    operators.TP3D_OT_popup_merge,
    operators.TP3D_OT_install_three_mf,
    operators.TP3D_OT_pick_gpx_file,
    operators.TP3D_OT_pick_svg_file,
    operators.TP3D_OT_check_update,
    operators.TP3D_OT_install_update,
    operators.TP3D_OT_open_premium_update,
    operators.TP3D_OT_dismiss_update,
    operators.TP3D_OT_remake_buildings,
    operators.TP3D_OT_remake_roads,
    operators.TP3D_OT_import_model_at_gps,
    operators.TP3D_OT_puzzle_configurator,
    operators.TP3D_OT_special_collection,
    operators.TP3D_OT_append_collection,
    operators.TP3D_OT_append_collection_blank,
]

_PREMIUM_CLASS_NAMES = [
    "TP3D_OT_terrain",
    "TP3D_OT_chain_generation",
    "TP3D_OT_city_coords",
    "TP3D_OT_merge_with_map",
    "TP3D_OT_generate_just_trail",
    "TP3D_OT_from_center_generation",
    "TP3D_OT_from_center_generation_with_trail",
    "TP3D_OT_2point_generation",
    "TP3D_OT_pick_geojson_file",
    "TP3D_OT_geojson_generation",
    "TP3D_OT_create_blank",
    "TP3D_OT_extend_tile",
    "TP3D_OT_import_height_map",
    "TP3D_OT_popup_heightmap",
    "TP3D_OT_map_picker",
]




@persistent
def startup_function(scene, dummy = None):

    print("Trailprint3D Launching Startup functions")

    for scn in bpy.data.scenes:
        props.repair_invalid_shape(scn)

    utils.loadCollections(scene, dummy)

    export.is_3mf_extension_installed()

    if const.ENABLE_UPDATE_CHECKER:
        if temp.PREMIUMVERSION:
            updater.start_premium_check()
        else:
            updater.start_check()

    #utils.load_myproperties_from_csv(bpy.context.scene.preset_list)

def register():
    # Ensure cache/preset dirs exist before anything else uses them.
    const._ensure_dirs()

    # Detect premium here — register() is called after Blender finishes reloading
    # all submodules, so temp.py can no longer reset PREMIUMVERSION to False after us.
    _addon_dir = os.path.dirname(__file__)
    temp.PREMIUMVERSION = os.path.exists(os.path.join(_addon_dir, "premium", "operators_pe.py"))

    ops_pe = None
    if temp.PREMIUMVERSION:
        try:
            import importlib
            importlib.import_module(".premium.utils_pe", __package__)   # loads into sys.modules
            ops_pe = importlib.import_module(".premium.operators_pe", __package__)
        except ImportError as e:
            print(f"TrailPrint3D: Error loading premium modules: {e}")
            temp.PREMIUMVERSION = False

    bpy.utils.register_class(addon_preferences.TP3D_AddonPreferences)
    bpy.utils.register_class(props.TP3D_PG_properties)
    bpy.app.translations.register(const.ADDON_NAME, translation.translations_dict)
    bpy.types.Scene.tp3d = bpy.props.PointerProperty(type=props.TP3D_PG_properties)
    bpy.types.Scene.preset_list = bpy.props.EnumProperty(
        name="Presets",
        items=utils.list_files_callback,
    )

    for cls in classes:
        bpy.utils.register_class(cls)

    if ops_pe:
        for name in _PREMIUM_CLASS_NAMES:
            cls = getattr(ops_pe, name, None)
            if cls:
                bpy.utils.register_class(cls)

    bpy.app.handlers.load_post.append(startup_function)

    # Populate special collections immediately so the UI isn't empty after a
    # reload. load_post only fires on the next file-open, so we schedule a
    # deferred call here that runs once the event loop is back and context is
    # fully available.
    bpy.app.timers.register(_load_collections_deferred, first_interval=0)

    # Check 3MF availability now — all addon modules are importable at this
    # point regardless of registration order, so addon_utils can find it.
    export.is_3mf_extension_installed()


def _load_collections_deferred():
    try:
        # Repairs the *already open* session too, not just future file loads
        # (load_post only fires on the next file-open) -- covers an addon
        # reload/update leaving `shape` pointed at a now-removed enum item.
        # Implicitly returns None, so the timer only runs once
        for scn in bpy.data.scenes:
            props.repair_invalid_shape(scn)
        utils.loadCollections(None, None)
    except (AttributeError, RuntimeError, ReferenceError) as e:
        print(f"TrailPrint3D: deferred collection load failed: {e}")


def unregister():
    bpy.app.translations.unregister(const.ADDON_NAME)

    if temp.PREMIUMVERSION:
        import sys
        ops_pe = sys.modules.get(f"{__package__}.premium.operators_pe")
        if ops_pe:
            for name in reversed(_PREMIUM_CLASS_NAMES):
                cls = getattr(ops_pe, name, None)
                if cls:
                    try:
                        bpy.utils.unregister_class(cls)
                    except RuntimeError:
                        pass

    for cls in reversed(classes):
        try:
            bpy.utils.unregister_class(cls)
        except RuntimeError:
            pass

    try:
        bpy.utils.unregister_class(props.TP3D_PG_properties)
    except RuntimeError:
        pass

    try:
        bpy.utils.unregister_class(addon_preferences.TP3D_AddonPreferences)
    except RuntimeError:
        pass

    try:
        bpy.app.handlers.load_post.remove(startup_function)
    except ValueError:
        pass

    try:
        del bpy.types.Scene.tp3d
    except AttributeError:
        pass

    try:
        del bpy.types.Scene.preset_list
    except AttributeError:
        pass

