#  Copyright (C) 2026  EmGi

# You are free to modify it under the terms of the GNU General Public License as published by the Free Software Foundation.
# You are free to use any models Generated by this Addon Commercially

import os

import bpy

ADDON_NAME = "TrailPrint3D"
ADDON_VERSION = (3, 2, 1)
required_blender_version = (5, 1, 0)

ENABLE_UPDATE_CHECKER = True

R = 6371.0  # Earth radius in kilometers

WATER_MAXSIZE = 500
SMALL_RIVERS_MAXSIZE = 50  # small/minor waterways drop out above this; big (wikidata) rivers + ponds still apply up to WATER_MAXSIZE
FOREST_MAXSIZE = 150
SCREE_MAXSIZE = 300
CITY_MAXSIZE = 50
GREENSPACE_MAXSIZE = 50
FARMLAND_MAXSIZE = 200
GLACIER_MAXSIZE = 1000
BUILDINGS_MAXSIZE = 60
BUILDINGS_MIN_PRINT_MM = 0.15 # Buildings whose PRINTED footprint side is smaller than this are culled, scales with map size.
LANDMARKS_MAXSIZE = 150
ROADS_MAXSIZE = 500
COASTLINE_MAXSIZE = 1000
STREETS_MAJOR_ONLY_THRESHOLD = 100   # above this mapsize: motorway+trunk only
STREETS_PRIMARY_THRESHOLD = 40       # above this mapsize: + primary+secondary

# Single-color element recess gap. The terrain recess cut for each color
# is dilated outward by toleranceElements * this factor. Setting to 0 will disable.
SCM_ELEMENT_GAP_FACTOR = 0.3

_elevation_cache = {}
specialCollection = []

# Define a path to store the counter data
counter_file = os.path.join(bpy.utils.user_resource('CONFIG'), "api_request_counter.json")

# Define a path to store the total maps generated counter
generation_counter_file = os.path.join(bpy.utils.user_resource('CONFIG'), "generation_counter.json")

#Set up a folder that holds all Cache Data
cache_dir = os.path.join(bpy.utils.user_resource('CONFIG'), "TrailPrint3D_Cache")

elevation_cache_file = os.path.join(bpy.utils.user_resource('CONFIG'), "TrailPrint3D_Cache","elevation_cache.json")

# Set up a cache directory for Terrarium tiles
terrarium_cache_dir = os.path.join(bpy.utils.user_resource('CONFIG'), "TrailPrint3D_Cache","terrarium_cache")

# Set up a cache for Overpass Files
overpass_cache_dir = os.path.join(bpy.utils.user_resource('CONFIG'), "TrailPrint3D_Cache","overpass_cache")

# Set up a cache for computed elevation arrays (per-map vertex elevations)
elevation_results_dir = os.path.join(bpy.utils.user_resource('CONFIG'), "TrailPrint3D_Cache","elevation_results")

#Set up a folder for Presets
preset_dir = os.path.join(bpy.utils.user_resource('CONFIG'), "TP3D-presets")


def _ensure_dirs():
    """Create addon cache/preset directories. Call from register() only."""
    os.makedirs(cache_dir, exist_ok=True)
    os.makedirs(terrarium_cache_dir, exist_ok=True)
    os.makedirs(overpass_cache_dir, exist_ok=True)
    os.makedirs(elevation_results_dir, exist_ok=True)
    os.makedirs(preset_dir, exist_ok=True)



