#  Copyright (C) 2026  EmGi

# You are free to modify it under the terms of the GNU General Public License as published by the Free Software Foundation.
# You are free to use any models Generated by this Addon Commercially

import bpy
from bpy.app.translations import pgettext_iface as _  #For Translation of Text Required
from bpy.props import (
    BoolProperty,
    EnumProperty,
    FloatProperty,
    IntProperty,
    PointerProperty,
    StringProperty,
)

from . import constants as const
from . import temp, utils


def shape_callback(self,context):
    #print(f"Shape: {self.shape}")
    #if self.shape == "HEXAGON INNER TEXT" or self.shape == "HEXAGON OUTER TEXT" or self.shape =="OCTAGON OUTER TEXT" or self.shape == "HEXAGON FRONT TEXT":
    #    try:
    #        bpy.utils.register_class(panels.TP3D_P_Shapes)
    #    except:
    #        pass
    #else:
    #    try:
    #        bpy.utils.unregister_class(panels.TP3D_P_Shapes)
    #    except:
    #        pass
    pass


def get_special_blend_items(self, context):
    # puzzles.blend itself (the hand-crafted jigsaw/sliding-puzzle templates)
    # stays Premium-exclusive and is stripped from free builds by build.py --
    # unlike the interactive Puzzle Generator, which is free. Items must be a
    # callback (not a static default) so this list can change per-build.
    #
    # Dynamic-items EnumProperty can't take an explicit `default=` -- Blender
    # always initializes to whichever item comes first here. Putting
    # puzzles.blend first for Premium preserves the original default; free
    # builds fall back to holder.blend since puzzles.blend isn't an option.
    if temp.PREMIUMVERSION:
        return [
            ("puzzles.blend", "Jigzaw/Sliding Puzzles", "global"),
            ("holder.blend", "Map Holder", "Latitudes -60 to 60"),
            ("connectors.blend", "Map Connectors", "Continental USA, Hawaii, parts of Alaska"),
        ]
    return [
        ("holder.blend", "Map Holder", "Latitudes -60 to 60"),
        ("connectors.blend", "Map Connectors", "Continental USA, Hawaii, parts of Alaska"),
    ]

def generation_mode_update(self, context):
    self.use_multi_generation = (self.generation_mode == 'MULTI')


# Which text/plate/shell extras each base shape supports. "NONE" (plain shape,
# no overlay) must come first in every list -- see the shapeTextStyle
# comment for why. HEART has no entry here -- it has no extras to offer.
_SHELL_ITEM = ("SHELL", _("Shell"), _("Snug protective shell around the map's sides and bottom, offset by the tolerance gap with a printable wall"))

SHAPE_TEXT_STYLES = {
    "HEXAGON": [
        ("NONE",        _("None"),        _("Plain hexagonal map, no text overlay")),
        ("INNER TEXT",  _("Inner text"),  _("Hexagonal map with inserted text")),
        ("OUTER TEXT",  _("Outer text"),  _("Hexagonal map with backplate and text")),
        ("FRONT TEXT",  _("Front text"),  _("Hexagonal map with backplate and text on the front")),
        _SHELL_ITEM,
    ],
    "OCTAGON": [
        ("NONE",       _("None"),        _("Plain octagon map, no text overlay")),
        ("OUTER TEXT", _("Outer text"),  _("Octagon map with backplate and text")),
        _SHELL_ITEM,
    ],
    "CIRCLE": [
        ("NONE",       _("None"),        _("Plain circular map, no text overlay")),
        ("OUTER TEXT", _("Outer text"),  _("Circular map with backplate and curved text")),
        _SHELL_ITEM,
    ],
    "SQUARE": [
        ("NONE", _("None"), _("Plain rectangular map, no extras")),
        _SHELL_ITEM,
    ],
    "ELLIPSE": [
        ("NONE", _("None"), _("Plain ellipse map, no extras")),
        _SHELL_ITEM,
    ],
}


def get_shape_text_style_items(self, context):
    # Items must be a callback (not a static list) since the available
    # styles depend on which base shape is currently selected.
    items = SHAPE_TEXT_STYLES.get(self.shape, [("NONE", _("None"), _("No text overlay available for this shape"))])
    if not temp.PREMIUMVERSION:
        # Shell is Premium-exclusive -- stays visible in the dropdown (so free
        # users know it exists) but gets a lock icon and a "(Premium)" label.
        # Blender's Enum dropdown can't disable a single item outright, so
        # actually picking it is caught by shape_text_style_update below,
        # which snaps the selection back to NONE.
        items = [
            (ident, _("%s (Premium)") % label, desc, 'LOCKED', i) if ident == "SHELL"
            else (ident, label, desc, 'NONE', i)
            for i, (ident, label, desc) in enumerate(items)
        ]
    return items


def shape_text_style_update(self, context):
    if self.shapeTextStyle == "SHELL" and not temp.PREMIUMVERSION:
        self.shapeTextStyle = "NONE"
        utils.show_message_box(
            _("Shell is a Patreon-exclusive feature."), "INFO", _("Premium Feature")
        )
        return
    # shapeTextStyle is a dynamic-items EnumProperty (see get_shape_text_style_items),
    # so Blender stores it as a bare index -- the identifier it resolves to depends
    # on whichever items list is current when read. shape_update (below) needs the
    # identifier the user actually *picked*, independent of that reinterpretation,
    # so mirror it into a plain string every time it's set while self.shape hasn't
    # changed yet (i.e. here, where the items list still matches the selection).
    self.shapeTextStyleCache = self.shapeTextStyle


def shape_update(self, context):
    # Switching self.shape changes shapeTextStyle's item list. Because that
    # property is stored as an index, re-reading self.shapeTextStyle here would
    # silently reinterpret the old index against the new list (e.g. index 2 means
    # "Outer text" under Hexagon but "Shell" under Octagon) instead of reflecting
    # what the user actually had selected. Use the cached identifier string
    # instead: keep it if the new shape still offers that option, else fall back
    # to None.
    valid_styles = {ident for ident, _label, _desc in SHAPE_TEXT_STYLES.get(self.shape, [])}
    cached = self.shapeTextStyleCache
    if cached == "SHELL" and not temp.PREMIUMVERSION:
        self.shapeTextStyle = "NONE"
    elif cached in valid_styles:
        self.shapeTextStyle = cached
    else:
        self.shapeTextStyle = "NONE"


def get_effective_shape(tp3d):
    """The full shape identifier generation.py/metadata.py operate on
    (e.g. "HEXAGON OUTER TEXT"), composed from the base shape dropdown and
    the text-style dropdown. Falls back to the bare base shape if no style
    is selected, or if the stored style isn't valid for the current base
    shape (e.g. left over from a different shape)."""
    base = tp3d.shape
    style = tp3d.shapeTextStyle
    if style == "SHELL" and not temp.PREMIUMVERSION:
        # Guards against a SHELL value left over from a Premium session/preset
        # -- Shell is Premium-exclusive, so free builds always fall back to
        # the bare base shape instead of acting on a stale selection.
        return base
    valid_styles = {ident for ident, _label, _desc in SHAPE_TEXT_STYLES.get(base, [])}
    if style and style != "NONE" and style in valid_styles:
        return f"{base} {style}"
    return base


def repair_invalid_shape(scene):
    """Files/sessions saved before the "... TEXT" shape variants were split
    out into shapeTextStyle may still have `shape` stored as one of those
    now-removed identifiers. Reading an EnumProperty whose stored index no
    longer exists in the (now trimmed, base-shapes-only) items list returns
    '' and logs a bpy.rna warning on every single access -- once per UI
    redraw, so it floods the console. Reset it once to a valid default so
    both the stored value and the warning spam go away."""
    tp3d = getattr(scene, "tp3d", None)
    if tp3d is not None and not tp3d.shape:
        tp3d.shape = "HEXAGON"


# Define a Property Group to store variables
class TP3D_PG_properties(bpy.types.PropertyGroup):
    file_path: StringProperty(
        name= _("File Path"),
        description= _("Select a GPX file"),
        default="",
        maxlen=1024,
    )# type: ignore
    export_path: StringProperty(
        name= _("Export Path"),
        description= _("Where to save the STL file"),
        default="",
        maxlen=1024,
        subtype='DIR_PATH'  # Enables folder selection
    )# type: ignore
    chain_path: StringProperty(
        name= _("Folder Path"),
        description= _("Select a folder that contains multiple GPX files"),
        default="",
        maxlen=1024,
        subtype='DIR_PATH'  # Enables folder selection
    )# type: ignore
    trailName: StringProperty(name= _("Name"), default="", description=_("Leave empty to use the Filename")) # type: ignore

    shape: EnumProperty(
        name = "Shape",
        items=[
            ("HEXAGON", _("Hexagon"), _("Hexagonal map")),
            ("SQUARE", _("Rectangle"), _("Rectangular map")),
            ("CIRCLE", _("Circle"), _("Circular map")),
            ("OCTAGON", _("Octagon"), _("Octagon Map")), #Premium
            ("ELLIPSE", _("Ellipse"), _("Ellipse Map")), #Premium
            ("HEART", _("Heart"), _("Heart Map")), #Premium
        ],
        default = "HEXAGON",
        update = shape_update,
    )# type: ignore
    shapeTextStyle: EnumProperty(
        name = _("Shape Extras"),
        description = _("Add an extra (text/plate overlay or shell) to the selected shape"),
        items = get_shape_text_style_items,
        update = shape_text_style_update,
        # Dynamic-items EnumProperty can't take an explicit `default=` -- see
        # get_special_blend_items above for why. "NONE" is first in every
        # per-shape list in SHAPE_TEXT_STYLES, so it's the default.
    )# type: ignore
    shapeTextStyleCache: StringProperty(default="NONE", options={'HIDDEN'}) # type: ignore

    api: bpy.props.EnumProperty(
        name = "api",
        items=[
            ("OPENTOPODATA", "Opentopodata", _("Slower but more accurate elevation")),
            ("OPEN-ELEVATION","Open-Elevation",_("Faster but some regions are low quality")),
            ("TERRAIN-TILES", "Terrain-Tiles", _("Currently Fastest available set")),
            ("MAPTERHORN", "Mapterhorn", _("Mapterhorn terrain tiles — 512px WebP, Terrarium encoding, free & open-source")),
            ("OPENTOPOGRAPHY", "OpenTopography", _("OpenTopography Global DEM API — requires API key for most datasets"))
        ],
        default = "MAPTERHORN"
    )# type: ignore

    openTopographyDataset: bpy.props.EnumProperty(
        name=_("Dataset"),
        items=[
            ("SRTMGL1",   "SRTM GL1 (30m)",    _("Global SRTM 30m resolution")),
            ("SRTMGL3",   "SRTM GL3 (90m)",    _("Global SRTM 90m resolution")),
            ("SRTM15Plus","SRTM15+ (500m)",     _("Global SRTM15+ 500m resolution — fastest download")),
            ("AW3D30",    "ALOS AW3D30 (30m)", _("Global ALOS World 3D 30m")),
            ("NASADEM",   "NASADEM (30m)",      _("NASA Digital Elevation Model 30m")),
            ("COP30",     "Copernicus 30m",     _("Copernicus DEM 30m")),
            ("COP90",     "Copernicus 90m",     _("Copernicus DEM 90m")),
        ],
        default="SRTMGL1"
    )# type: ignore

    apiRetries: IntProperty(name= _("Overpass API reuqest retries"), default = 5, min = 1, max = 20,description = _("How many Retries per Request before canceling")) # type: ignore

    dataset: EnumProperty(
        name = "Dataset",
        items=[
            ("srtm30m", "srtm30m", "Latitudes -60 to 60"),
            ("aster30m","aster30m","global"),
            ("ned10m","ned10m","Continental USA, Hawaii, parts of Alaska"),
            ("mapzen","mapzen","global"),
            ("nzdem8m","nzdem8m","New Zealand 8m"),
            ("eudem25m","eudem25m","Europe")
        ],
        default = "aster30m"
    )# type: ignore

    scalemode: EnumProperty(
        name= _("scalemode"),
        items=[
            ('FACTOR', _("Map Scale"), _("Set a scale based on the Map size")),
            ('COORDINATES', _("Coordinates"), _("Calculate the scale by using 2 Coordinates (Lat/lon)")),
            ('SCALE', _("Global Scale"), _("Set a scale based on the Global Scale (Mercator Projection)"))
        ],
        default='FACTOR'
    )# type: ignore
    pathScale: FloatProperty(name = _("Path Scale"), default = 0.8, min = 0.01, description = _("Scale of Path in Relation to the Mapsize/GlobalScale (depending on scalemode)")) # type: ignore
    scaleLon1: FloatProperty(name = "Lon1", default = 0, description = _("The Longitude of the first coordinate")) # type: ignore
    scaleLat1: FloatProperty(name = "Lat1", default = 0, description = _("The Latitude of the first coordinate")) # type: ignore
    scaleLon2: FloatProperty(name = "Lon2", default = 0, description = _("The Longitude of the second coordinate")) # type: ignore
    scaleLat2: FloatProperty(name = "Lat2", default = 0, description = _("The Latitude of the second coordinate")) # type: ignore

    selfHosted: StringProperty(name = _("Self Hosted API"), default="", description= _("Has to be same API format as Opentopodata.org (https://api.opentopodata.org/v1/)")) # type: ignore

    objSize: IntProperty(name= _("Object Size in mm"), default = 100, min = 5, max = 10000,description = _("Size of the map in mm")) # type: ignore
    num_subdivisions: IntProperty(name = _("Resolution"), default = 4, min = 1, max = 10, description = _("(max recommended 8) Higher Number = more detailed terrain but slower generation")) # type: ignore
    scaleElevation: FloatProperty(name = _("Elevation Scale"), default = 1, min = 0, max = 10000, description = _("Multiplier to the Elevation")) # type: ignore
    pathThickness: FloatProperty(name = _("Path Thickness"), default = 1.2, min = 0.1, max = 5, description = _("Thickness of the path in mm")) # type: ignore
    shapeRotation: IntProperty(name = _("ShapeRotation"), default = 0, min = -360, max = 360, description = _("Rotation of the shape") ) # type: ignore
    overwritePathElevation: BoolProperty(name= _("Overwrite Path Elevation"), default=True, description = _("Cast each point of the trail onto the Terrain Mesh")) # type: ignore
    o_verticesPath: StringProperty(name="Path vertices ", default="") # type: ignore
    o_verticesMap: StringProperty(name="Path Map ", default="") # type: ignore
    o_mapScale: StringProperty(name="Map Scale", default = "") # type: ignore
    o_time: StringProperty(name="TimeTook",default="") # type: ignore
    o_apiCounter_OpenTopoData: StringProperty(name="apiCounter_OpenTopodata", default = "API Limit: ---/1000 daily") # type: ignore
    o_apiCounter_OpenElevation: StringProperty(name="apiCounter_OpenElevation", default = "API Limit: ---/1000 monthly") # type: ignore
    o_mapsGenerated: StringProperty(name="MapsGenerated", default = "") # type: ignore
    o_centerx: FloatProperty(name = _("Center X"), default = 0, description = _("X Center of the Path")) # type: ignore
    o_centery: FloatProperty(name = _("Center Y"), default = 0, description = _("Y Center of the Path")) # type: ignore

    magnetHeight: FloatProperty(name = _("Magnet Height"), default = 2.5, description = _("Height of the Holes for Magnets")) # type: ignore
    magnetDiameter: FloatProperty(name = _("Magnet Diameter"), default = 6.3, description = _("Diameter of the Holes for Magnets")) # type: ignore

    bottomMarkCutout: BoolProperty(name=_("Bottom Mark Cutout"), default = False, description = _("Creates Bottom mark as a Cutout")) # type: ignore

    ellipseRatio: FloatProperty(name = _("Ellipse Aspect Ratio"), default = 0.75, description = _("0.75 means the ellipse height is 0.75 x objSize")) # type: ignore
    rectangleHeight: IntProperty(name = _("Rectangle Height"), default = 100, description = _("Height of the Rectangle")) # type: ignore

    textFont: StringProperty(
        name= _("Font"),
        description=_("Select a file"),
        default="",
        maxlen=1024,
        subtype='FILE_PATH'  # Enables file selection
    )# type: ignore
    textSize: IntProperty(name= _("Text Size"), default = 5, min = 0, max = 1000) # type: ignore
    textSizeTitle: IntProperty(name= _("Title Text Size"), default = 0, min = 0, max = 1000, description = _("Keep 0 to use value from 'Text Size'")) # type: ignore
    titlefield: StringProperty(name= _("title"), default= "{name}", description = _("Codes = | {name} | {length} | {elevation} |{date} | {speed} | {scale}")) # type: ignore
    textfield1: StringProperty(name= _("text1"), default = "{length}", description = _("Codes = | {name} | {length} | {elevation} |{date} | {speed} | {scale}")) # type: ignore
    textfield2: StringProperty(name= _("text2"), default = "{elevation}", description = _("Codes = | {name} | {length} | {elevation} |{date} | {speed} | {scale}")) # type: ignore
    textfield3: StringProperty(name= _("text3"), default = "{duration}", description = _("Codes = | {name} | {length} | {elevation} |{date} | {speed} | {scale}")) # type: ignore
    textfield4: StringProperty(name= _("text4"), default = "", description = _("Codes = | {name} | {length} | {elevation} |{date} | {speed} | {scale}")) # type: ignore
    textfield5: StringProperty(name= _("text5"), default = "", description = _("Codes = | {name} | {length} | {elevation} |{date} | {speed} | {scale}")) # type: ignore
    titleIcon: EnumProperty(
        name="Title Icon",
        items=[
            ('cycling', _("Cycling Icon"), _("Cycling Icon before the Title")),
            ('hiking', _("Hiking Icon"), _("Hiking Icon before the Title")),
            ('running', _("Running Icon"), _("Running Icon before the Title")),
            ('swimming', _("Swimming Icon"), _("Swimming Icon before the Title")),
            ('skiing', _("Skiing Icon"), _("Skiing Icon before the Title")),
            ('snowboarding', _("Snowboarding Icon"), _("Snowboarding Icon before the Title")),
            ('kajak', _("Kayak Icon"), _("Kayak Icon before the Title")),
            ('no', _("No Icon"), _("No icon before the Title"))
        ],
        default='no'
    )# type: ignore
    iconText1: EnumProperty(
        name="Text 1Icon",
        items=[
            ('distance', _("Distance Icon"), _("Distance Icon before the Text")),
            ('elevation', _("Elevation Icon"), _("Elevation Icon before the Text")),
            ('time', _("Time Icon"), _("Time icon before the Text")),
            ('speed', _("Speed Icon"), _("Speed icon before the Text")),
            ('date', _("Date Icon"), _("Date icon before the Text")),
            ('no', _("No Icon"), _("No icon before the Text"))
        ],
        default='distance'
    )# type: ignore
    iconText2: EnumProperty(
        name=_("Text 2 Icon"),
        items=[
            ('distance', _("Distance Icon"), _("Distance Icon before the Text")),
            ('elevation', _("Elevation Icon"), _("Elevation Icon before the Text")),
            ('time', _("Time Icon"), _("Time icon before the Text")),
            ('speed', _("Speed Icon"), _("Speed icon before the Text")),
            ('date', _("Date Icon"), _("Date icon before the Text")),
            ('no', _("No Icon"), _("No icon before the Text"))
        ],
        default='elevation'
    )# type: ignore
    iconText3: EnumProperty(
        name=_("Text 3 Icon"),
        items=[
            ('distance', _("Distance Icon"), _("Distance Icon before the Text")),
            ('elevation', _("Elevation Icon"), _("Elevation Icon before the Text")),
            ('time', _("Time Icon"), _("Time icon before the Text")),
            ('speed', _("Speed Icon"), _("Speed icon before the Text")),
            ('date', _("Date Icon"), _("Date icon before the Text")),
            ('no', _("No Icon"), _("No icon before the Text"))
        ],
        default='time'
    )# type: ignore
    iconText4: EnumProperty(
        name="Text 4 Icon",
        items=[
            ('distance', _("Distance Icon"), _("Distance Icon before the Text")),
            ('elevation', _("Elevation Icon"), _("Elevation Icon before the Text")),
            ('time', _("Time Icon"), _("Time icon before the Text")),
            ('speed', _("Speed Icon"), _("Speed icon before the Text")),
            ('date', _("Date Icon"), _("Date icon before the Text")),
            ('no', _("No Icon"), _("No icon before the Text"))
        ],
        default='no'
    )# type: ignore
    iconText5: EnumProperty(
        name="Text 5 Icon",
        items=[
            ('distance', _("Distance Icon"), _("Distance Icon before the Text")),
            ('elevation', _("Elevation Icon"), _("Elevation Icon before the Text")),
            ('time', _("Time Icon"), _("Time icon before the Text")),
            ('speed', _("Speed Icon"), _("Speed icon before the Text")),
            ('date', _("Date Icon"), _("Date icon before the Text")),
            ('no', _("No Icon"), _("No icon before the Text"))
        ],
        default='no'
    )# type: ignore

    svg_path: StringProperty(
        name= _("SVG Path"),
        description= _("Select a .SVG file"),
        default="",
        maxlen=1024,
    )# type: ignore

    #overwriteLength: StringProperty(name= _("text1"), default = "")
    #overwriteHeight: StringProperty(name= _("text2"), default = "")
    #overwriteTime: StringProperty(name= _("text3"), default = "")





    outerBorderSize: IntProperty(name= _("BorderSize in %"), default = 20, min = 0, max = 1000, description= _("Only for Shapes with Plate")) # type: ignore
    text_angle_preset: IntProperty(name= _("Text Angle"), description= _("Rotate Text on Shape"), default=0, min = 0, max = 260) # type: ignore
    plateThickness: FloatProperty(name= _("plateThickness"), default = 5, description= _("Thickness of the Additional Plate")) # type: ignore
    plateInsertValue: FloatProperty(name= _("plateInsertValue"), default = 0, description= _("Depth of Cutout for the Map in the Plate, 0  to ignore")) # type: ignore
    plateBevel: FloatProperty(name= _("Plate Bevel"), default = 0.0, min = 0.0, max = 50.0, description= _("Bevel the top and bottom edges of the plate (0 to disable)")) # type: ignore
    handleStyle: EnumProperty(
        name = _("Handle"),
        items=[
            ("NONE",  _("None"),  _("No handle")),
            ("ROUND", _("Round"), _("A round cylinder handle on top of the plate, like a medal")),
            ("FLAT",  _("Flat"),  _("A flat bar handle on top of the plate, like a medal")),
        ],
        default = "NONE",
    ) # type: ignore
    shellWallThickness: FloatProperty(name= _("Shell Wall Thickness"), default = 2.0, min = 0.1, description= _("Thickness of the Shell extra's side walls")) # type: ignore

    tileSpacing: FloatProperty(name= _("tileSpacing"), default = 0, description= _("Distance between Tiles when Extending")) # type: ignore



    minThickness: FloatProperty(name= _("minThickness"), default = 2, min = 0.5, max = 1000, description= _("Additional Thickness on lowest point")) # type: ignore
    xTerrainOffset: FloatProperty(name= _("xTerrainOffset"), default = 0, description= _("Gives the map an Offset in X-Direction from the path")) # type: ignore
    yTerrainOffset: FloatProperty(name= _("yTerrainOffset"), default = 0, description= _("Gives the map an Offset in Y-Direction from the path")) # type: ignore

    rescaleMultiplier: FloatProperty(name = _("scale"), default = 1, min = 0, max = 10000) # type: ignore
    thickenValue: FloatProperty(name= _("thickenValue"), default = 1, description = _("Makes your Map 1mm thicker")) # type: ignore
    fixedElevationScale: BoolProperty(name= _("FixedElevationScale(10mm)"), default=False, description = _("Force the elevation to be 10mm High from highest to lowest point (ElevationScale still applies after that)")) # type: ignore
    singleColorMode: BoolProperty(name= _("SingleColorMode Trail"), default = False, description = _("Enable this if you don't have a Multicolor printer")) # type: ignore
    singleColorModeHeight: FloatProperty(name= _("Trail Height"), default = 0.4, min=0.0, max=10.0, description = _("How far the SCM trail strip rises above the terrain surface (mm). 0 = flush with terrain. Works the same as Road Height.")) # type: ignore
    tolerance: FloatProperty(name= _("SingleColorMode Tolerance"), default = 0.2, description=_("Tolerance of the Trail for the SingleColorMode")) # type: ignore
    toleranceElements: FloatProperty(name= _("ToleranceElements"), default = 0.4, description= _("Tolerance of the Elements (Water, Forest) for the SingleColorMode")) # type: ignore
    disableCache: BoolProperty(name= _("disableCache"), default = False, description = _("Disable cache if you encounter random holes in your mesh")) # type: ignore
    disableElevationOutlierFix: BoolProperty(name= _("Disable Buggy Elevation Fixes"), default = False, description = _("Disable automatic correction of statistically outlying elevation values. Enable this if a real peak/valley is being incorrectly flattened")) # type: ignore
    ccacheSize: IntProperty(name = _("Cache Size"), default = 50000, min = 0) # type: ignore
    indipendendTiles : BoolProperty(name= _("IndipendendTiles"), default = False, description = _("Tile minThickness is independent from other tiles")) # type: ignore

    elementMode: EnumProperty(
        name="Element handling",
        items=[
            ('PAINT', _("Paint on Map"), _("Paint the Elements onto the map")),
            ('SINGLECOLORMODE_REMESH', _("Single-Color mode"), _("Use this SingleColorMode, if it causes problems try the other one")),
            #('SINGLECOLORMODE', _("SingleColor (Alternative)"), "Use this SingleColorMode if the other one causes problems"),
            ('SEPARATE', _("Separate objects"), _("Elements as separate objects (Increase Element Threshold to filter out unprintable element 'noise')"))
        ],
        default='PAINT'
    )# type: ignore
    elementModeInset: FloatProperty(name=_("Clip Inset"), default=2.0, min=0.0, description=_("Thickness of solid frame for SCM-elements"))# type: ignore


    col_wArea: FloatProperty(name= _("Water Threshold"), default = 1, description = _("Lakes smaller than the threshold won't be included")) # type: ignore
    col_wStreamWidth: FloatProperty(name= _("River Width"), default = 1.0, min=0.1, max=10.0, description = _("Adjusts the thickness of rivers and streams")) # type: ignore
    col_wPondsActive: BoolProperty(name= _("Water"), default=False, description = _("Include ponds and lakes (natural=water)")) # type: ignore
    col_wSmallRiversActive: BoolProperty(name= _("Small Rivers"), default=False, description = _("smaller Streams, canals, ditches and other minor waterways are not included in default water setting")) # type: ignore
    col_wBigRiversActive: BoolProperty(name= _("Big Rivers"), default=False, description = _("Major named rivers (waterway with wikidata tag. Usually already part of water setting)")) # type: ignore
    col_fActive: BoolProperty(name= _("Include Forests"), default=False, description = _("For Maps < 50Km Recommended")) # type: ignore
    col_fArea: FloatProperty(name= _("Threshold"), default = 10, description = _("Forests smaller than the threshold won't be included")) # type: ignore
    col_scrActive: BoolProperty(name= _("Include Scree"), default=False, description = _("Rocky/stony terrain. For Maps < 1000Km Recommended")) # type: ignore
    col_scrArea: FloatProperty(name= _("Threshold"), default = 1, description = _("Scree patches smaller than the threshold won't be included")) # type: ignore
    col_cActive: BoolProperty(name= _("Include City Boundaries"), default=False, description = _("For Maps < 100Km Recommended")) # type: ignore
    col_cArea: FloatProperty(name= _("Threshold"), default = 1, description = _("Cities smaller than the threshold won't be included")) # type: ignore
    col_grActive: BoolProperty(name= _("Include Greenspaces"), default=False, description = _("Parks, gardens, grass and other urban green areas. For Maps < 100Km Recommended")) # type: ignore
    col_grArea: FloatProperty(name= _("Threshold"), default = 1, description = _("Greenspaces smaller than the threshold won't be included")) # type: ignore
    col_faActive: BoolProperty(name= _("Include Farmland"), default=False, description = _("Fetches landuse=farmland and landuse=farmyard. For Maps < 1000Km Recommended")) # type: ignore
    col_faArea: FloatProperty(name= _("Threshold"), default = 1, description = _("Farmland patches smaller than the threshold won't be included")) # type: ignore
    col_glActive: BoolProperty(name= _("Include Glaciers"), default=False, description = _("For Maps < 1000Km Recommended")) # type: ignore
    col_glArea: FloatProperty(name= _("Threshold"), default = 1, description = _("Glaciers smaller than the threshold won't be included")) # type: ignore
    col_KeepManifold: BoolProperty(name= _("Keep Non-Manifold Objects"), default=False, description = _("Keep Broken/Non-Manifold objects")) # type: ignore
    el_bActive: BoolProperty(name= _("Include Buildings"), default=False, description = _("For Maps < 5Km Reccomended")) # type: ignore
    el_bHeightMultiplier: FloatProperty(name= _("Height Multiplier"), default=1.0, min=0.01, soft_max=10.0, description=_("Multiplies building height")) # type: ignore
    el_bMinPrintMM: FloatProperty(name= _("Min Footprint (mm)"), default=0.15, min=0.0, soft_max=5.0, precision=2, description=_("Buildings whose printed footprint side is smaller than this (in model mm) are skipped. Scale-aware: a larger real-world building on a bigger-km map prints smaller, so this threshold naturally culls more on larger maps.")) # type: ignore
    el_bRoofStyle: EnumProperty(
        name=_("Roof Style"),
        items=[
            ('FLAT', _("Flat"), _("Flat roof on every building")),
            ('PYRAMID', _("Pyramid"), _("Collapse each roof into a raised peak (tower-like skyline)")),
        ],
        default='FLAT'
    )# type: ignore
    el_bRoofHeight: FloatProperty(name=_("Roof Height"), default=15.0, min=0.0, max=100.0, subtype='PERCENTAGE', description=_("Pyramid roof peak height as a percentage of the building's own height")) # type: ignore
    el_lActive: BoolProperty(name= _("Include Landmarks"), default=False, description = _("OSM attractions, monuments, castles, cathedrals, stadiums, lighthouses, peaks and towers. Area landmarks get their real footprints, point landmarks become small markers. For Maps < 150Km Recommended")) # type: ignore
    el_lHeightMultiplier: FloatProperty(name= _("Height Multiplier"), default=2.0, min=0.01, soft_max=10.0, description=_("Multiplies landmark height so they stand out above surrounding buildings")) # type: ignore
    el_lBaseMM: FloatProperty(name= _("Point Base Size (mm)"), default=1.0, min=0.1, soft_max=10.0, precision=1, description=_("Printed base diameter of markers for point landmarks without a footprint")) # type: ignore
    el_lNodeHeightMM: FloatProperty(name= _("Min Marker Height (mm)"), default=2.0, min=0.0, soft_max=20.0, precision=1, description=_("Minimum printed height of point landmark markers")) # type: ignore
    el_lMaxNodes: IntProperty(name= _("Max Point Landmarks"), default=150, min=0, soft_max=1000, description=_("Cap on point landmark markers per map (tallest kept first). 0 = unlimited")) # type: ignore

    el_sMultiplier: FloatProperty(name= _("Road Width Multiplier"), default = 1, description = _("To make Roads thicker or thinner")) # type: ignore
    el_sMinWidthMM: FloatProperty(name= _("Min Road Width (mm)"), default = 0.2, min=0.0, soft_max=5.0, precision=2, description=_("Minimum printed half-width roads are clamped to. Raise for chunkier, more printable streets on city maps")) # type: ignore
    el_sHeight: FloatProperty(name= _("Road Height"), default = 0.4, min=0.0, description = _("Height of road geometry above terrain")) # type: ignore
    el_sCutTolerance: FloatProperty(name= _("Road Cutout Tolerance"), default = 0.2, min=0.0, description = _("Extra clearance added around roads when cutting their footprint out of terrain/elements in SEPARATE/SingleColorMode, so the printed road piece seats without an overly tight fit. Same idea as Tolerance Elements, but for roads.")) # type: ignore
    el_sExcludeAlleys: BoolProperty(name= _("Exclude Alleys/Driveways"), default=True, description = _("Drops OSM highway=service ways explicitly tagged service=alley, service=driveway, service=parking_aisle, or service=drive-through -- the actual back-alley/driveway/parking-lot clutter -- while keeping plain service roads. Uses OSM's own tagging instead of guessing from geometry (a single street is often split into many short ways at every intersection, so filtering by length would wrongly cull real streets too).")) # type: ignore

    show_water: BoolProperty(name= _("Water & Ocean"), default=False) # type: ignore
    show_roads: BoolProperty(name= _("Roads"), default=False) # type: ignore
    el_sBigActive: BoolProperty(name= _("Big Roads"), default=False, description = f"primary, motorway, primary_link, motorway_link — limited to motorway only on maps < {const.ROADS_MAXSIZE}km") # type: ignore
    el_sMedActive: BoolProperty(name= _("Medium Roads"), default=False, description = f"secondary, tertiary, secondary_link, tertiary_link — ignored on maps < {const.STREETS_MAJOR_ONLY_THRESHOLD}km") # type: ignore
    el_sSmallActive: BoolProperty(name= _("Small Roads"), default=False, description = f"residential, living_street — ignored on maps < {const.STREETS_PRIMARY_THRESHOLD}km") # type: ignore
    el_sServiceActive: BoolProperty(name= _("Service Roads"), default=False, description = f"highway=service -- vehicle access roads to buildings, parking lots, business estates (see Key:service on the OSM wiki). Split out from Small Roads since it needs its own alley/driveway/parking_aisle sub-tag filtering (see Exclude Alleys/Driveways) rather than being lumped in with named residential streets. Ignored on maps < {const.STREETS_PRIMARY_THRESHOLD}km") # type: ignore
    el_sFootwaysActive: BoolProperty(name= _("Footways/Sidewalks"), default=False, description = f"highway=footway -- pedestrian sidewalks and paths, OSM's own separate non-vehicle category (see Key:highway on the OSM wiki). Kept out of Small Roads by default since footways trace almost every street and are usually the biggest single source of visual clutter. Ignored on maps < {const.STREETS_PRIMARY_THRESHOLD}km") # type: ignore
    el_oActive: BoolProperty(name=_("Include Ocean"), default=False, description=_("Generate ocean surface cut along the coastline. Experimental")) # type: ignore
    el_oMinIslandArea: FloatProperty(name=_("Min Island Area"), default=2.0, min=0.0, soft_max=100.0, description=_("Islands smaller than this area (in map units²) are not punched out of the ocean. At a 100mm map size, 1 map unit ≈ 1mm on the print, so the default 2.0 ≈ a ~1.4×1.4mm patch. Set to 0 to punch all islands.")) # type: ignore
    el_oRdpEpsilon: FloatProperty(name=_("Coastline Simplify"), default=0.1, min=0.0, soft_max=2.0, precision=3, description=_("Douglas-Peucker simplification tolerance (map units) applied to the coastline before building the ocean. Higher = fewer points but can introduce self-intersections on convoluted coasts. Set to 0 to disable simplification. Testing aid.")) # type: ignore
    mountain_treshold:IntProperty(name= _("Mountain Threshold"), default = 60, min = 0, max = 100,subtype='PERCENTAGE', description= _("Height Threshold to Color Mountains")) # type: ignore
    cl_thickness: FloatProperty(name= _("Contour Line Thickness (mm)"), default = 0.2, description = _("Thickness of the Contour Line")) # type: ignore
    cl_distance: FloatProperty(name= _("Contour Line distance"), default = 2, description = _("Distance between Contour lines")) # type: ignore
    cl_offset: FloatProperty(name= _("Contour Line offset"), default = 0.0, description = _("Offset of the Contour lines")) # type: ignore
    cl_useRealMeters: BoolProperty(name= _("Use Real-World Meters"), default = True, description = _("Interpret the Contour Line distance/offset as real-world elevation meters instead of mm on the printed model")) # type: ignore

    generation_mode: EnumProperty(
        name="Generation Mode",
        items=[
            ('GENERATION', _("Trail"), _("Single GPX file generation")),
            ('MULTI', _("Multi Trail"), _("Chain multiple GPX files")),
            ('TERRAIN', _("Terrain"), _("Generate terrain without GPX")),
        ],
        default='GENERATION',
        update=generation_mode_update
    )# type: ignore

    show_create_settings: BoolProperty(name=_("General Settings"), default=True) # type: ignore
    show_terrain_files: BoolProperty(name=_("Files"), default=True) # type: ignore
    show_export: BoolProperty(name=_("Export"), default=True) # type: ignore
    disable_auto_export: BoolProperty(name=_("Disable Auto Export"), default=False, description=_("Don't automatically export files after generation")) # type: ignore
    disable_3mf_export: BoolProperty(name=_("Disable 3MF Export"), default=False, description=_("Don't use 3MF format even if the addon is installed")) # type: ignore

    show_stats: BoolProperty(name= _("Additional Info"), default=False) # type: ignore
    show_coloring: BoolProperty(name= _("Elements"), default=False) # type: ignore
    show_chain: BoolProperty(name= _("Multi Generation"), default=False) # type: ignore
    use_multi_generation: BoolProperty(name= _("Multi Generation"), default=False) # type: ignore
    show_map: BoolProperty(name= _("Map"),default=False) # type: ignore
    show_pin: BoolProperty(name= _("Pin"),default=False) # type: ignore
    show_special: BoolProperty(name= _("Special"),default=False) # type: ignore
    show_postProcess: BoolProperty(name= _("Post Process"), default = False) # type: ignore
    show_api: BoolProperty(name= _("API"), default=False) # type: ignore
    show_attribution: BoolProperty(name= _("Attribution"), default = False) # type: ignore
    show_preset: BoolProperty(name= _("Preset"), default=False) # type: ignore

    cityname: StringProperty(name= _("Cityname"), default="Berlin", description = _("Get coordinates of a City")) # type: ignore
    pinLat: FloatProperty(name= _("Latitude"), default = 48.00) # type: ignore
    pinLon: FloatProperty(name= _("Longitude"), default = 8.00) # type: ignore

    pinCutout: BoolProperty(name= _("Pin Cutout"), default=False, description=_("When placing a pin, also cut a matching socket into the map and elements at the pin's position, so the printed pin can be inserted afterward")) # type: ignore
    pinCutoutClearance: FloatProperty(name= _("Cutout Clearance"), default=0.2, min=0.0, soft_max=2.0, description=_("Extra size added to the cutout so the printed pin actually fits into the socket")) # type: ignore

    show_models: BoolProperty(name= _("3D Models"), default=False) # type: ignore
    mdlPath: StringProperty(name=_("Model File"), default="", subtype='FILE_PATH', description=_("STL or OBJ file placed at the given GPS coordinates")) # type: ignore
    mdlLat: FloatProperty(name= _("Latitude"), default = 48.00) # type: ignore
    mdlLon: FloatProperty(name= _("Longitude"), default = 8.00) # type: ignore
    mdlScale: FloatProperty(name= _("Scale"), default = 1.0, min=0.001, soft_max=100.0, description=_("Uniform scale applied to the imported model")) # type: ignore
    mdlDrapeToTerrain: BoolProperty(name= _("Drape to Terrain"), default=True, description=_("Drop the model onto the map surface at its GPS position. Disable to place at the given height")) # type: ignore
    mdlHeight: FloatProperty(name= _("Height"), default = 0.0, description=_("Base height of the model when Drape to Terrain is off")) # type: ignore

    mapmode: EnumProperty(
        name=_("mapmode"),
        items=[
            ('FROMPLANE', _("From Selected"), _("Generate the Map from a Flat Plane")),
            ('FROMCENTER', _("Center + Radius"), _("Generate the Map from a Point coordinate and a Radius")),
            ('2POINTS', _("2 Points"), _("Generate the Map from 2 Coordinates")),
            ('GEOJSON', _("GeoJSON Boundary"), _("Generate the Map clipped to a GeoJSON polygon boundary")),
        ],
        default='FROMPLANE'
    )# type: ignore

    geojsonFilePath: StringProperty(name=_("GeoJSON File"), default="", description=_("Path(s) to the imported .geojson boundary file(s), \"|\"-joined when more than one was selected")) # type: ignore
    geojsonSimplifyTolerance: FloatProperty(name=_("Simplify Tolerance"), default=0.1, min=0.0, soft_max=5.0, precision=3, description=_("Douglas-Peucker simplification tolerance (map units) applied to the imported boundary. Higher = fewer points but can introduce self-intersections on convoluted borders. Set to 0 to disable simplification.")) # type: ignore
    geojsonPointCount: IntProperty(name=_("Boundary Points"), default=0, description=_("Number of points in the boundary after simplification (read-only, set after import)")) # type: ignore
    geojsonAreaKm: FloatProperty(name=_("Detected Area"), default=0.0, description=_("Real-world size of the imported boundary in km (read-only, set after import)")) # type: ignore

    jMapLat: FloatProperty(name="Latitude", default = 49.00) # type: ignore
    jMapLon: FloatProperty(name="Longitude", default = 9.00) # type: ignore
    jMapRadius: FloatProperty(name="Radius im Km", default = 200) # type: ignore

    jMapLat1: FloatProperty(name="Latitude1", default = 48.00) # type: ignore
    jMapLat2: FloatProperty(name="Latitude2", default = 49.00) # type: ignore
    jMapLon1: FloatProperty(name="Longitude1", default = 8.00) # type: ignore
    jMapLon2: FloatProperty(name="Longitude2", default = 9.00) # type: ignore


    specialBlendFile: EnumProperty(
        name="Category",
        description= _("Choose what you want to import"),
        items=get_special_blend_items,
        update = utils.loadCollections

    )# type: ignore

    # Custom property to store selection
    specialCollectionName: EnumProperty(
        name="specialCollection",
        description= _("Choose a collection from the external .blend"),
        #items=dynamic_specialCollection_items
        items=lambda self, context: const.specialCollection
    )# type: ignore



    #OTHER VARIABLES
    sRunDuration: IntProperty(name="runDuration", default = 0, description = "how long the script was running") # type: ignore
    sAdditionalExtrusion: FloatProperty(name="sAdditionalExtrusion",default = 0) # type: ignore
    sAutoScale: FloatProperty(name="sAutoScale",default = 1) # type: ignore
    sScaleHor: FloatProperty(name="sScaleHor",default = 1, description = "Scale of the Map") # type: ignore
    sMapInKm: FloatProperty(name = "Map Length", default = 0, description = "How much Km are the equivalent of the Map Size") # type: ignore
    sTime_str: StringProperty(name="time_str", default="") # type: ignore
    modelname: StringProperty(name="modelname",default="") # type: ignore
    total_length: FloatProperty(name="total_length",default = 0) # type: ignore
    total_elevation: FloatProperty(name="total_elevation",default = 0) # type: ignore
    total_time: FloatProperty(name="total_time",default = 0) # type: ignore
    average_speed: FloatProperty(name="average_speed",default = 0) # type: ignore
    trail_date: StringProperty(name="trail_date",default = "") # type: ignore

    lowestZ: FloatProperty(name="lowestZ",default = 0) # type: ignore
    highestZ: FloatProperty(name="highestZ",default = 0) # type: ignore
    buggyDataset: BoolProperty(name="buggyDataset",default = 0) # type: ignore

    minLat: FloatProperty(name="minLat",default = 0) # type: ignore
    maxLat: FloatProperty(name="maxLat",default = 0) # type: ignore
    minLon: FloatProperty(name="minLon",default = 0) # type: ignore
    maxLon: FloatProperty(name="maxLon",default = 0) # type: ignore

    exportformat: StringProperty(name="exportformat",default = "STL") # type: ignore
    opentopoAdress: StringProperty(name="opentopoAdress", default = "https://api.opentopodata.org/v1/") # type: ignore

    currentMap: PointerProperty(name = "Map object", type = bpy.types.Object) # type: ignore
    currentTrail: PointerProperty(name="Trail object", type = bpy.types.Object) # type: ignore
